version: '3'

services:
    web:
        build:
          context: ./
        container_name: ${APPNAME}-web
        image: php-custom
        ports:
            - "80:80"
        networks:
            - php-net
        volumes:
            - vol-src:/var/www/html
    db:
        container_name: ${APPNAME}-db
        image: mariadb
        restart: always
        networks:
            - php-net
        volumes:
            - vol-db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
networks:
    php-net:

volumes:
    vol-src:
        driver: local
    vol-db:
        driver: local
