services:
    web:
        platform: linux/x86_64
        container_name: ps9-web
        image: prestashop/prestashop:9.0.x-apache
        networks:
            - ps-net
        volumes:
            - ps9-web:/var/www/html
        depends_on:  
            - db
        ports:
            - "8080:80"
        environment:
            - DB_SERVER=ps9-db
            - PS_DEV_MODE=1
            - PS_FOLDER_ADMIN=admin-dev
    db:
        platform: linux/x86_64
        container_name: ps9-db
        image: mariadb
        tty: true
        networks:
            - ps-net
        volumes:
            - ps9-db:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=ps9_db
            - MYSQL_ROOT_PASSWORD=admin
networks:
    ps-net:

volumes:
    ps9-db:
        driver: local
    ps9-web:
        driver: local
